#
# MM25 v1.1 configuration
#

# metadata
dataset_metadata: '/data/clean/geo/metadata.tsv'
phenotype_metadata: '/data/fassoc/mm25/1.2/metadata/association_metadata.feather'

# gene-level results
gene_pvals_indiv: '/data/fassoc/mm25/1.2/merged/mm25_gene_association_pvals.feather'
gene_pvals_combined: '/data/proj/mm25/1.2/all/mm25_gene_scores.feather'

# pathway-level results
pathway_pvals_indiv: '/data/fassoc/mm25/1.2/merged/mm25_pathway_association_pvals.feather'
pathway_pvals_combined: '/data/proj/mm25/1.2/all/mm25_pathway_scores.feather'

# dataset config dir
dataset_cfg_dir: '~/d/r/nih/fassoc/datasets/mm25/1.2'

# functional enrichment results
fgsea_results_combined: '/data/fgsea/mm25/1.2/results/merged/mm25_gene_scores.parquet'
fgsea_results_indiv: '/data/fgsea/mm25/1.2/results/merged/mm25_gene_association_pvals.parquet'

fgsea_summary_combined: '/data/fgsea/mm25/1.2/results/summary/mm25_gene_scores_summary.tsv'
fgsea_summary_indiv: '/data/fgsea/mm25/1.2/results/summary/mm25_gene_association_pvals_summary.tsv'
